"""Init(): Migration

Revision ID: 83723ba49c14
Revises: 
Create Date: 2021-11-15 02:01:01.594559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83723ba49c14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('genre_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('genre_id')
    )
    op.create_table('movies',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=5), nullable=True),
    sa.Column('rating', sa.DECIMAL(precision=10, scale=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], ),
    sa.PrimaryKeyConstraint('movie_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    op.drop_table('genre')
    # ### end Alembic commands ###
