"""Added(): Genre Table

Revision ID: c8e0ff52401d
Revises: b5e4c7c35814
Create Date: 2021-11-13 15:41:50.697628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8e0ff52401d'
down_revision = 'b5e4c7c35814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('genre_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('genre_id')
    )
    op.add_column('movies', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('movies', sa.Column('genre_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'movies', 'genre', ['genre_id'], ['genre_id'])
    op.drop_column('movies', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('genre', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.drop_column('movies', 'genre_id')
    op.drop_column('movies', 'is_active')
    op.drop_table('genre')
    # ### end Alembic commands ###
